#  This file defines the structure of dataset.

columns :
  longitude : float
  latitude: float
  housing_median_age : float
  total_rooms : float
  total_bedrooms : float
  population : float
  households : float
  median_income : float
  median_house_value : float
  ocean_proximity : category

target_column : median_house_value

# Domain value defines that for categorical column what values can be accepted.

domain_value :
  ocean_proximity :
    - <1H OCEAN
    - INLAND
    - ISLAND
    - NEAR BAY
    - NEAR OCEAN